# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeepTootController.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DeepTootController import Ui_DeepTootController
import gui_functions


class Ui_DeepTootControllerFull(Ui_DeepTootController):
    def set_event_handling(self):
        self.pushButton_execute.clicked.connect(gui_functions.print_hello)